{% set name = "darth-d" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/darth-d-{{ version }}.tar.gz
  sha256: 4003422b4315c98406cd8b9b4e02dd2e6dd894eabec1e93325d797561f95e18f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - napari
    - napari-plugin-engine  # Imported but not listed as requirement
    - napari-tools-menu     # Imported but not listed as requirement
    - numpy
    - openai >=1.2.0
    - pillow
    - python >={{ python_min }}
    - scikit-image          # Imported but not listed as requirement
    - stackview >=0.7.1

test:
  imports:
    - darth_d
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/darth-d
  summary: A simple to use image generator based on OpenAIs DALL-E
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/haesleinhuepf/darth-d

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
